### ISSUE TITLE
[Feature request] Possibility to generate multiple files in order to split the execution

### ISSUE THREAD

**Issue by lhimo** [tomaszpolanski/faster_driver#20]
We have a very large suite, and running in debug mode is taking way too long. We would like to split the execution into more than one file.

Proposition:
Allow an argument to be passed to fasterdriver saying in how many files you want to split the final merged file.

**Comment by tomaszpolanski** [comment]
Currently, the tool supports running tests by folder, so you can only run specific folders.
Additionally, there is sharding so if you want to split execution on your CI you can also do that. 
Wouldn't that already solve your issue?

**Comment by lhimo** [comment]
That's exactly what I needed, I forgot it was there. Awesome, thanks!
